// This file was automatically generated by graphql transpiler

export enum TagFormat {
    NORMAL = 'NORMAL',
    READABLE = 'READABLE',
}

export enum ResetCodeSendMethod {
    EMAIL = 'EMAIL',
    SMS = 'SMS',
}

export enum ComparisonOperator {
    LESS_THAN = 'LESS_THAN',
    GREATER_THAN = 'GREATER_THAN',
}

export enum UserTypes {
    VENDOR_ADMIN = 'VENDOR_ADMIN',
    VENDOR_EMPLOYEE = 'VENDOR_EMPLOYEE',
    CUSTOMER = 'CUSTOMER',
    MASTER = 'MASTER',
    INVALID = 'INVALID',
}

export enum LoyaltyTransactionType {
    EARNING = 'EARNING',
    EARNING_FRIEND = 'EARNING_FRIEND',
    SHARING = 'SHARING',
    REDEEMING = 'REDEEMING',
}

export enum LoyaltyProgramType {
    DOLLAR = 'DOLLAR',
    ORDER = 'ORDER',
    ITEM = 'ITEM',
}

export enum ReferralTransactionType {
    FIRST_REFERRAL = 'FIRST_REFERRAL',
    REGULAR_REFERRAL = 'REGULAR_REFERRAL',
}

export enum PayoutPaymentMethod {
    MANUAL = 'MANUAL',
}

export enum PayoutStatus {
    PENDING = 'PENDING',
    IN_TRANSIT = 'IN_TRANSIT',
    PAID = 'PAID',
    CANCELLED = 'CANCELLED',
}

export enum PayoutAutoRequestSchedule {
    OFF = 'OFF',
    WEEKLY = 'WEEKLY',
    BI_WEEKLY = 'BI_WEEKLY',
    MONTHLY = 'MONTHLY',
}

export enum ReloadWalletPaymentMethod {
    CREDIT_CARD = 'CREDIT_CARD',
    APPLE_PAY = 'APPLE_PAY',
    ANDROID_PAY = 'ANDROID_PAY',
}

export enum WhereFilterGroupOperator {
    AND = 'AND',
    OR = 'OR',
}

export enum WhereFilterOperator {
    EQUALS = 'EQUALS',
    REGEX = 'REGEX',
    GREATER_THAN = 'GREATER_THAN',
    GREATER_THAN_OR_EQUAL = 'GREATER_THAN_OR_EQUAL',
    LESS_THAN = 'LESS_THAN',
    LESS_THAN_OR_EQUAL = 'LESS_THAN_OR_EQUAL',
    EXISTS = 'EXISTS',
    DOES_NOT_EXIST = 'DOES_NOT_EXIST',
    NOT_EQUALS = 'NOT_EQUALS',
}

export enum ServiceChargeType {
    CREDIT = 'CREDIT',
    DEBIT = 'DEBIT',
}

export enum ServiceChargeReason {
    ORDER_TRANSACTION_FEE = 'ORDER_TRANSACTION_FEE',
    PAYOUT_REQUEST_FEE = 'PAYOUT_REQUEST_FEE',
    OTHER = 'OTHER',
    OTHER_TAXABLE = 'OTHER_TAXABLE',
    TAX = 'TAX',
}

export enum VendorAnalyticsCustomerType {
    FIRST_TIME = 'FIRST_TIME',
    CASUAL = 'CASUAL',
    REGULAR = 'REGULAR',
}

export enum VendorApprovalStatus {
    NOT_APPROVED = 'NOT_APPROVED',
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
}

export enum UiBaseDisplayType {
    RESTAURANT = 'RESTAURANT',
    QSR = 'QSR',
}

export enum VendorStatus {
    OPEN = 'OPEN',
    CLOSED = 'CLOSED',
    HIDDEN = 'HIDDEN',
    NOT_ACCEPTING = 'NOT_ACCEPTING',
    LEAVE = 'LEAVE',
}

export enum OrderCancellationReason {
    VENDOR_CANCELLED = 'VENDOR_CANCELLED',
    VENDOR_PREP_CANCELLED = 'VENDOR_PREP_CANCELLED',
    VENDOR_ITEM_SOLD_OUT = 'VENDOR_ITEM_SOLD_OUT',
    VENDOR_STORE_CLOSING_SOON = 'VENDOR_STORE_CLOSING_SOON',
    CUSTOMER_NOT_PICKED_UP = 'CUSTOMER_NOT_PICKED_UP',
    CUSTOMER_CANCELLED = 'CUSTOMER_CANCELLED',
    OTHER = 'OTHER',
}

export enum OrderType {
    EAT_IN = 'EAT_IN',
    TAKE_OUT = 'TAKE_OUT',
    DELIVERY = 'DELIVERY',
    SELF_DELIVERY = 'SELF_DELIVERY',
}

export enum OrderPaymentMethod {
    CREDIT_CARD = 'CREDIT_CARD',
    WALLET = 'WALLET',
    IN_PERSON = 'IN_PERSON',
}

export enum OrderModifierChoiceType {
    ADD = 'ADD',
    NO = 'NO',
    DEFAULT = 'DEFAULT',
}

export enum OrderStatusIdentifier {
    PLACED = 'PLACED',
    PREPARING = 'PREPARING',
    PREPARED = 'PREPARED',
    COMPLETE = 'COMPLETE',
    CANCELLED = 'CANCELLED',
}

export enum FlashSaleType {
    DOLLAR = 'DOLLAR',
    PERCENTAGE = 'PERCENTAGE',
}

export enum SurveyDeliveryRule {
    AFTER_ORDER = 'AFTER_ORDER',
    MANUAL = 'MANUAL',
}

export enum SurveyQuestionType {
    CHECKBOX = 'CHECKBOX',
    MULTI_CHECKBOX = 'MULTI_CHECKBOX',
    SHORT_ANSWER = 'SHORT_ANSWER',
    RATING = 'RATING',
}

export enum CategoryType {
    REGULAR = 'REGULAR',
    DAILY_SPECIALS = 'DAILY_SPECIALS',
}

export enum DelivererProfileApprovalStatus {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    SUSPENDED = 'SUSPENDED',
}

export enum DelivererAvailabilityStatus {
    AVAILABLE = 'AVAILABLE',
    NOT_AVAILABLE = 'NOT_AVAILABLE',
}

export enum DelivererProfileType {
    REGULAR = 'REGULAR',
    PARTNER = 'PARTNER',
}

export enum DeliveryRequestStatus {
    PENDING = 'PENDING',
    ACCEPTED = 'ACCEPTED',
    REJECTED = 'REJECTED',
}

export enum DeliveryStatus {
    DELIVERER_REQUESTED = 'DELIVERER_REQUESTED',
    DELIVERER_FOUND = 'DELIVERER_FOUND',
    PICKED_UP = 'PICKED_UP',
    RECEIVED_BY_VENDOR = 'RECEIVED_BY_VENDOR',
    DELIVERING = 'DELIVERING',
    DELIVERED = 'DELIVERED',
}

export enum ShiftTimePeriodType {
    WORK = 'WORK',
    BREAK = 'BREAK',
}

export enum EmployeeLanguage {
    EN = 'EN',
    FR = 'FR',
    ZH = 'ZH',
}

export enum EmployeeRole {
    ADMIN = 'ADMIN',
    USER = 'USER',
}

export enum DominantHand {
    RIGHT = 'RIGHT',
    LEFT = 'LEFT',
}

export enum EmploymentStatus {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
}

export enum CountryCode {
    US = 'US',
    AF = 'AF',
    AX = 'AX',
    AL = 'AL',
    DZ = 'DZ',
    AS = 'AS',
    AD = 'AD',
    AO = 'AO',
    AI = 'AI',
    AQ = 'AQ',
    AG = 'AG',
    AR = 'AR',
    AM = 'AM',
    AW = 'AW',
    AU = 'AU',
    AT = 'AT',
    AZ = 'AZ',
    BS = 'BS',
    BH = 'BH',
    BD = 'BD',
    BB = 'BB',
    BY = 'BY',
    BE = 'BE',
    BZ = 'BZ',
    BJ = 'BJ',
    BM = 'BM',
    BT = 'BT',
    BO = 'BO',
    BQ = 'BQ',
    BA = 'BA',
    BW = 'BW',
    BV = 'BV',
    BR = 'BR',
    IO = 'IO',
    BN = 'BN',
    BG = 'BG',
    BF = 'BF',
    BI = 'BI',
    KH = 'KH',
    CM = 'CM',
    CA = 'CA',
    CV = 'CV',
    KY = 'KY',
    CF = 'CF',
    TD = 'TD',
    CL = 'CL',
    CN = 'CN',
    CX = 'CX',
    CC = 'CC',
    CO = 'CO',
    KM = 'KM',
    CG = 'CG',
    CD = 'CD',
    CK = 'CK',
    CR = 'CR',
    CI = 'CI',
    HR = 'HR',
    CU = 'CU',
    CW = 'CW',
    CY = 'CY',
    CZ = 'CZ',
    DK = 'DK',
    DJ = 'DJ',
    DM = 'DM',
    DO = 'DO',
    EC = 'EC',
    EG = 'EG',
    SV = 'SV',
    GQ = 'GQ',
    ER = 'ER',
    EE = 'EE',
    ET = 'ET',
    FK = 'FK',
    FO = 'FO',
    FJ = 'FJ',
    FI = 'FI',
    FR = 'FR',
    GF = 'GF',
    PF = 'PF',
    TF = 'TF',
    GA = 'GA',
    GM = 'GM',
    GE = 'GE',
    DE = 'DE',
    GH = 'GH',
    GI = 'GI',
    GR = 'GR',
    GL = 'GL',
    GD = 'GD',
    GP = 'GP',
    GU = 'GU',
    GT = 'GT',
    GG = 'GG',
    GN = 'GN',
    GW = 'GW',
    GY = 'GY',
    HT = 'HT',
    HM = 'HM',
    VA = 'VA',
    HN = 'HN',
    HK = 'HK',
    HU = 'HU',
    IS = 'IS',
    IN = 'IN',
    ID = 'ID',
    IR = 'IR',
    IQ = 'IQ',
    IE = 'IE',
    IM = 'IM',
    IL = 'IL',
    IT = 'IT',
    JM = 'JM',
    JP = 'JP',
    JE = 'JE',
    JO = 'JO',
    KZ = 'KZ',
    KE = 'KE',
    KI = 'KI',
    KR = 'KR',
    KP = 'KP',
    KW = 'KW',
    KG = 'KG',
    LA = 'LA',
    LV = 'LV',
    LB = 'LB',
    LS = 'LS',
    LR = 'LR',
    LY = 'LY',
    LI = 'LI',
    LT = 'LT',
    LU = 'LU',
    MO = 'MO',
    MK = 'MK',
    MG = 'MG',
    MW = 'MW',
    MY = 'MY',
    MV = 'MV',
    ML = 'ML',
    MT = 'MT',
    MH = 'MH',
    MQ = 'MQ',
    MR = 'MR',
    MU = 'MU',
    YT = 'YT',
    MX = 'MX',
    FM = 'FM',
    MD = 'MD',
    MC = 'MC',
    MN = 'MN',
    ME = 'ME',
    MS = 'MS',
    MA = 'MA',
    MZ = 'MZ',
    MM = 'MM',
    NA = 'NA',
    NR = 'NR',
    NP = 'NP',
    NL = 'NL',
    NC = 'NC',
    NZ = 'NZ',
    NI = 'NI',
    NE = 'NE',
    NG = 'NG',
    NU = 'NU',
    NF = 'NF',
    MP = 'MP',
    NO = 'NO',
    OM = 'OM',
    PK = 'PK',
    PW = 'PW',
    PS = 'PS',
    PA = 'PA',
    PG = 'PG',
    PY = 'PY',
    PE = 'PE',
    PH = 'PH',
    PN = 'PN',
    PL = 'PL',
    PT = 'PT',
    PR = 'PR',
    QA = 'QA',
    RE = 'RE',
    RO = 'RO',
    RU = 'RU',
    RW = 'RW',
    BL = 'BL',
    SH = 'SH',
    KN = 'KN',
    LC = 'LC',
    MF = 'MF',
    PM = 'PM',
    VC = 'VC',
    WS = 'WS',
    SM = 'SM',
    ST = 'ST',
    SA = 'SA',
    SN = 'SN',
    RS = 'RS',
    SC = 'SC',
    SL = 'SL',
    SG = 'SG',
    SX = 'SX',
    SK = 'SK',
    SI = 'SI',
    SB = 'SB',
    SO = 'SO',
    ZA = 'ZA',
    GS = 'GS',
    SS = 'SS',
    ES = 'ES',
    LK = 'LK',
    SD = 'SD',
    SR = 'SR',
    SJ = 'SJ',
    SZ = 'SZ',
    SE = 'SE',
    CH = 'CH',
    SY = 'SY',
    TW = 'TW',
    TJ = 'TJ',
    TZ = 'TZ',
    TH = 'TH',
    TL = 'TL',
    TG = 'TG',
    TK = 'TK',
    TO = 'TO',
    TT = 'TT',
    TN = 'TN',
    TR = 'TR',
    TM = 'TM',
    TC = 'TC',
    TV = 'TV',
    UG = 'UG',
    UA = 'UA',
    AE = 'AE',
    GB = 'GB',
    UM = 'UM',
    UY = 'UY',
    UZ = 'UZ',
    VU = 'VU',
    VE = 'VE',
    VN = 'VN',
    VG = 'VG',
    VI = 'VI',
    WF = 'WF',
    EH = 'EH',
    YE = 'YE',
    ZM = 'ZM',
    ZW = 'ZW',
}

export enum MenuItemStatus {
    AVAILABLE = 'AVAILABLE',
    UNAVAILABLE = 'UNAVAILABLE',
}

export enum FeeType {
    PERCENTAGE = 'PERCENTAGE',
    FIXED = 'FIXED',
}

export enum FeeReason {
    OTHER = 'OTHER',
    GLOBAL_TAX = 'GLOBAL_TAX',
}

export enum CouponTransactionType {
    PURCHASE = 'PURCHASE',
    RELOAD = 'RELOAD',
    CREATE = 'CREATE',
}

export enum CouponType {
    VALUE = 'VALUE',
    PERCENTAGE = 'PERCENTAGE',
}

