// This file was automatically generated by graphql transpiler

export enum TagFormat {
    NORMAL = 'NORMAL',
    READABLE = 'READABLE',
}

export enum ResetCodeSendMethod {
    EMAIL = 'EMAIL',
    SMS = 'SMS',
}

export enum ComparisonOperator {
    LESS_THAN = 'LESS_THAN',
    GREATER_THAN = 'GREATER_THAN',
}

export enum UserTypes {
    VENDOR_ADMIN = 'VENDOR_ADMIN',
    VENDOR_EMPLOYEE = 'VENDOR_EMPLOYEE',
    CUSTOMER = 'CUSTOMER',
    MASTER = 'MASTER',
    INVALID = 'INVALID',
}

export enum LoyaltyTransactionType {
    EARNING = 'EARNING',
    EARNING_FRIEND = 'EARNING_FRIEND',
    SHARING = 'SHARING',
    REDEEMING = 'REDEEMING',
}

export enum LoyaltyProgramType {
    DOLLAR = 'DOLLAR',
    ORDER = 'ORDER',
    ITEM = 'ITEM',
}

export enum PayoutMethod {
    MANUAL = 'MANUAL',
}

export enum PayoutStatus {
    PENDING = 'PENDING',
    IN_TRANSIT = 'IN_TRANSIT',
    PAID = 'PAID',
    CANCELLED = 'CANCELLED',
}

export enum PayoutAutoRequestSchedule {
    OFF = 'OFF',
    WEEKLY = 'WEEKLY',
    BI_WEEKLY = 'BI_WEEKLY',
    MONTHLY = 'MONTHLY',
}

export enum WhereFilterGroupOperator {
    AND = 'AND',
    OR = 'OR',
}

export enum WhereFilterOperator {
    EQUALS = 'EQUALS',
    REGEX = 'REGEX',
    GREATER_THAN = 'GREATER_THAN',
    GREATER_THAN_OR_EQUAL = 'GREATER_THAN_OR_EQUAL',
    LESS_THAN = 'LESS_THAN',
    LESS_THAN_OR_EQUAL = 'LESS_THAN_OR_EQUAL',
    EXISTS = 'EXISTS',
    DOES_NOT_EXIST = 'DOES_NOT_EXIST',
    NOT_EQUALS = 'NOT_EQUALS',
}

export enum ServiceChargeType {
    CREDIT = 'CREDIT',
    DEBIT = 'DEBIT',
}

export enum ServiceChargeReason {
    ORDER_TRANSACTION_FEE = 'ORDER_TRANSACTION_FEE',
    PAYOUT_REQUEST_FEE = 'PAYOUT_REQUEST_FEE',
    OTHER = 'OTHER',
    OTHER_TAXABLE = 'OTHER_TAXABLE',
    TAX = 'TAX',
}

export enum VendorAnalyticsCustomerType {
    FIRST_TIME = 'FIRST_TIME',
    CASUAL = 'CASUAL',
    REGULAR = 'REGULAR',
}

export enum VendorApprovalStatus {
    NOT_APPROVED = 'NOT_APPROVED',
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
}

export enum UiBaseDisplayType {
    RESTAURANT = 'RESTAURANT',
    QSR = 'QSR',
}

export enum VendorStatus {
    OPEN = 'OPEN',
    CLOSED = 'CLOSED',
    HIDDEN = 'HIDDEN',
    NOT_ACCEPTING = 'NOT_ACCEPTING',
    LEAVE = 'LEAVE',
}

export enum OrderCancellationReason {
    VENDOR_CANCELLED = 'VENDOR_CANCELLED',
    VENDOR_PREP_CANCELLED = 'VENDOR_PREP_CANCELLED',
    VENDOR_ITEM_SOLD_OUT = 'VENDOR_ITEM_SOLD_OUT',
    VENDOR_STORE_CLOSING_SOON = 'VENDOR_STORE_CLOSING_SOON',
    CUSTOMER_NOT_PICKED_UP = 'CUSTOMER_NOT_PICKED_UP',
    CUSTOMER_CANCELLED = 'CUSTOMER_CANCELLED',
    OTHER = 'OTHER',
}

export enum OrderType {
    EAT_IN = 'EAT_IN',
    TAKE_OUT = 'TAKE_OUT',
    DELIVERY = 'DELIVERY',
    SELF_DELIVERY = 'SELF_DELIVERY',
}

export enum OrderPaymentMethod {
    CREDIT_CARD = 'CREDIT_CARD',
    WALLET = 'WALLET',
    IN_PERSON = 'IN_PERSON',
}

export enum FlashSaleType {
    DOLLAR = 'DOLLAR',
    PERCENTAGE = 'PERCENTAGE',
}

export enum SurveyDeliveryRule {
    AFTER_ORDER = 'AFTER_ORDER',
}

export enum SurveyQuestionType {
    CHECKBOX = 'CHECKBOX',
    MULTI_CHECKBOX = 'MULTI_CHECKBOX',
    SHORT_ANSWER = 'SHORT_ANSWER',
    RATING = 'RATING',
}

export enum CategoryType {
    REGULAR = 'REGULAR',
    DAILY_SPECIALS = 'DAILY_SPECIALS',
}

export enum DelivererProfileApprovalStatus {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    SUSPENDED = 'SUSPENDED',
}

export enum DelivererAvailabilityStatus {
    AVAILABLE = 'AVAILABLE',
    NOT_AVAILABLE = 'NOT_AVAILABLE',
}

export enum DelivererProfileType {
    REGULAR = 'REGULAR',
    PARTNER = 'PARTNER',
}

export enum DeliveryRequestStatus {
    PENDING = 'PENDING',
    ACCEPTED = 'ACCEPTED',
    REJECTED = 'REJECTED',
}

export enum DeliveryStatus {
    DELIVERER_REQUESTED = 'DELIVERER_REQUESTED',
    DELIVERER_FOUND = 'DELIVERER_FOUND',
    PICKED_UP = 'PICKED_UP',
    RECEIVED_BY_VENDOR = 'RECEIVED_BY_VENDOR',
    DELIVERING = 'DELIVERING',
    DELIVERED = 'DELIVERED',
}

export enum ShiftTimePeriodType {
    WORK = 'WORK',
    BREAK = 'BREAK',
}

export enum CountryCode {
    UNITEDSTATES = 'US',
    AFGHANISTAN = 'AF',
    ALANDISLANDS = 'AX',
    ALBANIA = 'AL',
    ALGERIA = 'DZ',
    AMERICANSAMOA = 'AS',
    ANDORRA = 'AD',
    ANGOLA = 'AO',
    ANGUILLA = 'AI',
    ANTARCTICA = 'AQ',
    ANTIGUAANDBARBUDA = 'AG',
    ARGENTINA = 'AR',
    ARMENIA = 'AM',
    ARUBA = 'AW',
    AUSTRALIA = 'AU',
    AUSTRIA = 'AT',
    AZERBAIJAN = 'AZ',
    BAHAMAS = 'BS',
    BAHRAIN = 'BH',
    BANGLADESH = 'BD',
    BARBADOS = 'BB',
    BELARUS = 'BY',
    BELGIUM = 'BE',
    BELIZE = 'BZ',
    BENIN = 'BJ',
    BERMUDA = 'BM',
    BHUTAN = 'BT',
    BOLIVIA = 'BO',
    BONAIRESINTEUSTATIUSSABA = 'BQ',
    BOSNIAANDHERZEGOVINA = 'BA',
    BOTSWANA = 'BW',
    BOUVETISLAND = 'BV',
    BRAZIL = 'BR',
    BRITISHINDIANOCEANTERRITORY = 'IO',
    BRUNEIDARUSSALAM = 'BN',
    BULGARIA = 'BG',
    BURKINAFASO = 'BF',
    BURUNDI = 'BI',
    CAMBODIA = 'KH',
    CAMEROON = 'CM',
    CANADA = 'CA',
    CAPEVERDE = 'CV',
    CAYMANISLANDS = 'KY',
    CENTRALAFRICANREPUBLIC = 'CF',
    CHAD = 'TD',
    CHILE = 'CL',
    CHINA = 'CN',
    CHRISTMASISLAND = 'CX',
    COCOSKEELINGISLANDS = 'CC',
    COLOMBIA = 'CO',
    COMOROS = 'KM',
    CONGO = 'CG',
    CONGODEMOCRATICREPUBLIC = 'CD',
    COOKISLANDS = 'CK',
    COSTARICA = 'CR',
    COTEDIVOIRE = 'CI',
    CROATIA = 'HR',
    CUBA = 'CU',
    CURAÇAO = 'CW',
    CYPRUS = 'CY',
    CZECHREPUBLIC = 'CZ',
    DENMARK = 'DK',
    DJIBOUTI = 'DJ',
    DOMINICA = 'DM',
    DOMINICANREPUBLIC = 'DO',
    ECUADOR = 'EC',
    EGYPT = 'EG',
    ELSALVADOR = 'SV',
    EQUATORIALGUINEA = 'GQ',
    ERITREA = 'ER',
    ESTONIA = 'EE',
    ETHIOPIA = 'ET',
    FALKLANDISLANDS = 'FK',
    FAROEISLANDS = 'FO',
    FIJI = 'FJ',
    FINLAND = 'FI',
    FRANCE = 'FR',
    FRENCHGUIANA = 'GF',
    FRENCHPOLYNESIA = 'PF',
    FRENCHSOUTHERNTERRITORIES = 'TF',
    GABON = 'GA',
    GAMBIA = 'GM',
    GEORGIA = 'GE',
    GERMANY = 'DE',
    GHANA = 'GH',
    GIBRALTAR = 'GI',
    GREECE = 'GR',
    GREENLAND = 'GL',
    GRENADA = 'GD',
    GUADELOUPE = 'GP',
    GUAM = 'GU',
    GUATEMALA = 'GT',
    GUERNSEY = 'GG',
    GUINEA = 'GN',
    GUINEABISSAU = 'GW',
    GUYANA = 'GY',
    HAITI = 'HT',
    HEARDISLANDMCDONALDISLANDS = 'HM',
    HOLYSEEVATICANCITYSTATE = 'VA',
    HONDURAS = 'HN',
    HONGKONG = 'HK',
    HUNGARY = 'HU',
    ICELAND = 'IS',
    INDIA = 'IN',
    INDONESIA = 'ID',
    IRAN = 'IR',
    IRAQ = 'IQ',
    IRELAND = 'IE',
    ISLEOFMAN = 'IM',
    ISRAEL = 'IL',
    ITALY = 'IT',
    JAMAICA = 'JM',
    JAPAN = 'JP',
    JERSEY = 'JE',
    JORDAN = 'JO',
    KAZAKHSTAN = 'KZ',
    KENYA = 'KE',
    KIRIBATI = 'KI',
    KOREA = 'KR',
    KOREADEMOCRATICPEOPLESREPUBLIC = 'KP',
    KUWAIT = 'KW',
    KYRGYZSTAN = 'KG',
    LAOPEOPLESDEMOCRATICREPUBLIC = 'LA',
    LATVIA = 'LV',
    LEBANON = 'LB',
    LESOTHO = 'LS',
    LIBERIA = 'LR',
    LIBYANARABJAMAHIRIYA = 'LY',
    LIECHTENSTEIN = 'LI',
    LITHUANIA = 'LT',
    LUXEMBOURG = 'LU',
    MACAO = 'MO',
    MACEDONIA = 'MK',
    MADAGASCAR = 'MG',
    MALAWI = 'MW',
    MALAYSIA = 'MY',
    MALDIVES = 'MV',
    MALI = 'ML',
    MALTA = 'MT',
    MARSHALLISLANDS = 'MH',
    MARTINIQUE = 'MQ',
    MAURITANIA = 'MR',
    MAURITIUS = 'MU',
    MAYOTTE = 'YT',
    MEXICO = 'MX',
    MICRONESIA = 'FM',
    MOLDOVA = 'MD',
    MONACO = 'MC',
    MONGOLIA = 'MN',
    MONTENEGRO = 'ME',
    MONTSERRAT = 'MS',
    MOROCCO = 'MA',
    MOZAMBIQUE = 'MZ',
    MYANMAR = 'MM',
    NAMIBIA = 'NA',
    NAURU = 'NR',
    NEPAL = 'NP',
    NETHERLANDS = 'NL',
    NEWCALEDONIA = 'NC',
    NEWZEALAND = 'NZ',
    NICARAGUA = 'NI',
    NIGER = 'NE',
    NIGERIA = 'NG',
    NIUE = 'NU',
    NORFOLKISLAND = 'NF',
    NORTHERNMARIANAISLANDS = 'MP',
    NORWAY = 'NO',
    OMAN = 'OM',
    PAKISTAN = 'PK',
    PALAU = 'PW',
    PALESTINIANTERRITORY = 'PS',
    PANAMA = 'PA',
    PAPUANEWGUINEA = 'PG',
    PARAGUAY = 'PY',
    PERU = 'PE',
    PHILIPPINES = 'PH',
    PITCAIRN = 'PN',
    POLAND = 'PL',
    PORTUGAL = 'PT',
    PUERTORICO = 'PR',
    QATAR = 'QA',
    REUNION = 'RE',
    ROMANIA = 'RO',
    RUSSIANFEDERATION = 'RU',
    RWANDA = 'RW',
    SAINTBARTHELEMY = 'BL',
    SAINTHELENA = 'SH',
    SAINTKITTSANDNEVIS = 'KN',
    SAINTLUCIA = 'LC',
    SAINTMARTIN = 'MF',
    SAINTPIERREANDMIQUELON = 'PM',
    SAINTVINCENTANDGRENADINES = 'VC',
    SAMOA = 'WS',
    SANMARINO = 'SM',
    SAOTOMEANDPRINCIPE = 'ST',
    SAUDIARABIA = 'SA',
    SENEGAL = 'SN',
    SERBIA = 'RS',
    SEYCHELLES = 'SC',
    SIERRALEONE = 'SL',
    SINGAPORE = 'SG',
    SINTMAARTEN = 'SX',
    SLOVAKIA = 'SK',
    SLOVENIA = 'SI',
    SOLOMONISLANDS = 'SB',
    SOMALIA = 'SO',
    SOUTHAFRICA = 'ZA',
    SOUTHGEORGIAANDSANDWICHISL = 'GS',
    SOUTHSUDAN = 'SS',
    SPAIN = 'ES',
    SRILANKA = 'LK',
    SUDAN = 'SD',
    SURINAME = 'SR',
    SVALBARDANDJANMAYEN = 'SJ',
    SWAZILAND = 'SZ',
    SWEDEN = 'SE',
    SWITZERLAND = 'CH',
    SYRIANARABREPUBLIC = 'SY',
    TAIWAN = 'TW',
    TAJIKISTAN = 'TJ',
    TANZANIA = 'TZ',
    THAILAND = 'TH',
    TIMORLESTE = 'TL',
    TOGO = 'TG',
    TOKELAU = 'TK',
    TONGA = 'TO',
    TRINIDADANDTOBAGO = 'TT',
    TUNISIA = 'TN',
    TURKEY = 'TR',
    TURKMENISTAN = 'TM',
    TURKSANDCAICOSISLANDS = 'TC',
    TUVALU = 'TV',
    UGANDA = 'UG',
    UKRAINE = 'UA',
    UNITEDARABEMIRATES = 'AE',
    UNITEDKINGDOM = 'GB',
    UNITEDSTATESOUTLYINGISLANDS = 'UM',
    URUGUAY = 'UY',
    UZBEKISTAN = 'UZ',
    VANUATU = 'VU',
    VENEZUELA = 'VE',
    VIETNAM = 'VN',
    VIRGINISLANDSBRITISH = 'VG',
    VIRGINISLANDSUS = 'VI',
    WALLISANDFUTUNA = 'WF',
    WESTERNSAHARA = 'EH',
    YEMEN = 'YE',
    ZAMBIA = 'ZM',
    ZIMBABWE = 'ZW',
}
