name: Publish SDK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Existing Github action to checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        # Existing Github action to setup NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install npm-cli-login
        run: npm install -g npm-cli-login
      - name: Authenticate to GitHub Packages
        run: npm-cli-login -u $GITHUB_USERNAME -p $GITHUB_TOKEN -e $GITHUB_EMAIL -r https://npm.pkg.github.com
        env: 
          GITHUB_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
          GITHUB_EMAIL: ${{ secrets.PUBLISH_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.LOGIN_TOKEN }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
