name: Publish SDK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Existing Github action to checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        # Existing Github action to setup NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PAT }}
      - name: Build
        run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PAT }}
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
